// mockSongs.js
export const mockSongs = [
  {
    id: 'fnaf',
    title: "Five Nights at Freddy's",
    artist: "The Living Tombstone",
    album: "Five Nights at Freddy's",
    duration: "2:45",
    durationSec: 165,
    cover: "linear-gradient(135deg, #1f2937 0%, #111827 50%, #312e81 100%)",
    gradientColors: ["#1f2937", "#111827", "#312e81"],
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3", // Working public audio stream
    lyrics: [
      { time: 0, text: "♫ (Intro Instrumental) ♫" },
      { time: 8, text: "We're waiting every night" },
      { time: 10.5, text: "To finally roam and invite" },
      { time: 13, text: "Newcomers to play with us" },
      { time: 16, text: "For many years we've been all alone" },
      { time: 19, text: "We're forced to be still and play" },
      { time: 21.5, text: "The same songs we've known since that day" },
      { time: 24.5, text: "An imposter took our life away" },
      { time: 27, text: "Now we're stuck here to decay" },
      { time: 30, text: "Please let us get in!" },
      { time: 32.5, text: "Don't lock us away!" },
      { time: 35, text: "We're not like what you're thinking" },
      { time: 37.5, text: "We are poor little souls" },
      { time: 40, text: "Who have lost all control" },
      { time: 42, text: "And we're forced here to take that role" },
      { time: 46, text: "We've been all alone" },
      { time: 48, text: "In our little zone" },
      { time: 51, text: "Since nineteen eighty-seven" },
      { time: 54, text: "Join us, be our friend" },
      { time: 57, text: "Or just be stuck and defend" },
      { time: 59.5, text: "After all you only got" },
      { time: 62.5, text: "Five Nights at Freddy's" },
      { time: 65, text: "Is this where you want to be?" },
      { time: 67.5, text: "I just don't get it" },
      { time: 69, text: "Why do you want to stay" },
      { time: 71, text: "Five Nights at Freddy's" },
      { time: 74, text: "You should have looked for another job" },
      { time: 79, text: "You should have said to this place good-bye" },
      { time: 84.5, text: "It's like there's so much more" },
      { time: 87, text: "Maybe you've been in this place before" },
      { time: 90, text: "♫ (Electronic Break) ♫" },
      { time: 104, text: "We remember a face" },
      { time: 106.5, text: "Of a man in a purple grace" },
      { time: 109, text: "He came and he took us down" },
      { time: 111.5, text: "With a smile on his face, a frown" },
      { time: 114.5, text: "But we're here to say" },
      { time: 117, text: "That you won't get away" },
      { time: 119, text: "With the games that you play today" },
      { time: 122, text: "After all you only got" },
      { time: 125, text: "Five Nights at Freddy's" },
      { time: 128, text: "Is this where you want to be?" },
      { time: 130, text: "I just don't get it" },
      { time: 132, text: "Why do you want to stay" },
      { time: 134, text: "Five Nights at Freddy's" },
      { time: 137, text: "You should have looked for another job" },
      { time: 142.5, text: "You should have said to this place good-bye" },
      { time: 148, text: "♫ (Outro) ♫" }
    ]
  },
  {
    id: 'nekozilla',
    title: "Nekozilla",
    artist: "Different Heaven",
    album: "NCS Release",
    duration: "2:48",
    durationSec: 168,
    cover: "linear-gradient(135deg, #ec4899 0%, #be185d 50%, #4c0519 100%)",
    gradientColors: ["#ec4899", "#be185d", "#4c0519"],
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3",
    lyrics: [
      { time: 0, text: "♫ (Intro Synth Melody) ♫" },
      { time: 10, text: "Welcome to the world of Nekozilla" },
      { time: 15, text: "Feel the retro synthesizers roll" },
      { time: 20, text: "Moving to the beat, we lose control" },
      { time: 25, text: "♫ (Upbeat Electronic Drop) ♫" },
      { time: 48, text: "Dancing in the neon-lit arcade" },
      { time: 53, text: "Memories that we will never fade" },
      { time: 58, text: "Nekozilla, guide us through the night" },
      { time: 63, text: "Everything is gonna be alright" },
      { time: 68, text: "♫ (Chiptune Lead Break) ♫" },
      { time: 92, text: "Can you hear the cats meowing?" },
      { time: 96, text: "Can you feel the rhythm growing?" },
      { time: 100, text: "We are neon, we are bright!" },
      { time: 105, text: "♫ (High Energy Climax Drop) ♫" },
      { time: 140, text: "Fading out into the quiet sky" },
      { time: 145, text: "Nekozilla says goodbye..." }
    ]
  },
  {
    id: 'violin',
    title: "World's Smallest Violin",
    artist: "AJR",
    album: "OK ORCHESTRA",
    duration: "3:00",
    durationSec: 180,
    cover: "linear-gradient(135deg, #f59e0b 0%, #d97706 50%, #78350f 100%)",
    gradientColors: ["#f59e0b", "#d97706", "#78350f"],
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3",
    lyrics: [
      { time: 0, text: "♫ (Ukelele Plucking Intro) ♫" },
      { time: 5, text: "My grandpa fought in World War Two" },
      { time: 8, text: "He was such a noble guy" },
      { time: 11, text: "I think about him all the time" },
      { time: 14, text: "And it makes me want to cry" },
      { time: 17, text: "And my father had a business" },
      { time: 20, text: "That went under in the fall" },
      { time: 23, text: "I write these little songs, it's true" },
      { time: 26, text: "But they don't matter much at all" },
      { time: 29, text: "So I play my world's smallest violin" },
      { time: 33, text: "For the troubles that I'm currently in" },
      { time: 37, text: "And I know that it sounds silly" },
      { time: 40, text: "But I think it is a sin" },
      { time: 42.5, text: "If I blow up into smithereens" },
      { time: 45, text: "And spew my tiny orchestra" },
      { time: 48, text: "All over the bedroom floor" },
      { time: 51, text: "♫ (Upbeat Trumpets) ♫" }
    ]
  },
  {
    id: 'unity',
    title: "Unity",
    artist: "TheFatRat",
    album: "Unity Single",
    duration: "4:09",
    durationSec: 249,
    cover: "linear-gradient(135deg, #10b981 0%, #059669 50%, #064e3b 100%)",
    gradientColors: ["#10b981", "#059669", "#064e3b"],
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3",
    lyrics: [
      { time: 0, text: "♫ (Atmospheric Piano Intro) ♫" },
      { time: 12, text: "Stand together, we are one" },
      { time: 17, text: "Underneath the rising sun" },
      { time: 22, text: "We will build a brand new day" },
      { time: 27, text: "Find our unity, find our way" },
      { time: 32, text: "♫ (Massive Glitch Hop Lead Drop) ♫" },
      { time: 64, text: "No more barriers, no more lies" },
      { time: 69, text: "Looking forward to the skies" },
      { time: 74, text: "Every voice will join the song" },
      { time: 79, text: "Here is where we all belong" },
      { time: 84, text: "♫ (Melodic Drop Loop) ♫" }
    ]
  },
  {
    id: 'courtesy',
    title: "Courtesy Call",
    artist: "Thousand Foot Krutch",
    album: "The End Is Where We Begin",
    duration: "3:56",
    durationSec: 236,
    cover: "linear-gradient(135deg, #3b82f6 0%, #1d4ed8 50%, #1e3a8a 100%)",
    gradientColors: ["#3b82f6", "#1d4ed8", "#1e3a8a"],
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3",
    lyrics: [
      { time: 0, text: "♫ (Radio Crackle / Heavy Drums Intro) ♫" },
      { time: 8, text: "I hope you're ready for a courtesy call" },
      { time: 12, text: "This is the wake-up, the warning for all" },
      { time: 16, text: "We're going in, we're breaking the wall" },
      { time: 20, text: "Listen closely to the courtesy call" },
      { time: 24, text: "♫ (Heavy Alt-Rock Guitar Riff) ♫" },
      { time: 40, text: "It's time to choose, it's time to fight" },
      { time: 44, text: "We will shine a burning light" },
      { time: 48, text: "No surrender, stand up tall" },
      { time: 52, text: "This is your official courtesy call!" }
    ]
  },
  {
    id: 'allstar',
    title: "All Star",
    artist: "Smash Mouth",
    album: "Astro Lounge",
    duration: "3:20",
    durationSec: 200,
    cover: "linear-gradient(135deg, #f97316 0%, #ea580c 50%, #7c2d12 100%)",
    gradientColors: ["#f97316", "#ea580c", "#7c2d12"],
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3",
    lyrics: [
      { time: 0, text: "Somebody once told me" },
      { time: 2, text: "The world is gonna roll me" },
      { time: 4, text: "I ain't the sharpest tool in the shed" },
      { time: 7, text: "She was looking kind of dumb" },
      { time: 9, text: "With her finger and her thumb" },
      { time: 11, text: "In the shape of an \"L\" on her forehead" },
      { time: 14, text: "Well, the years start coming" },
      { time: 16, text: "And they don't stop coming" },
      { time: 18, text: "Fed to the rules and I hit the ground running" },
      { time: 21, text: "Didn't make sense not to live for fun" },
      { time: 23, text: "Your brain gets smart but your head gets dumb" },
      { time: 26, text: "So much to do, so much to see" },
      { time: 28, text: "So what's wrong with taking the backstreets?" },
      { time: 31, text: "You'll never know if you don't go" },
      { time: 33.5, text: "You'll never shine if you don't glow" },
      { time: 36, text: "Hey now, you're an all star" },
      { time: 38.5, text: "Get your game on, go play" },
      { time: 41, text: "Hey now, you're a rock star" },
      { time: 43.5, text: "Get the show on, get paid" },
      { time: 46, text: "And all that glitters is gold" },
      { time: 49.5, text: "Only shooting stars break the mold" }
    ]
  },
  {
    id: 'lightemup',
    title: "My Songs Know What You Did In The Dark",
    artist: "Fall Out Boy",
    album: "Save Rock and Roll",
    duration: "3:07",
    durationSec: 187,
    cover: "linear-gradient(135deg, #ef4444 0%, #dc2626 50%, #7f1d1d 100%)",
    gradientColors: ["#ef4444", "#dc2626", "#7f1d1d"],
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-7.mp3",
    lyrics: [
      { time: 0, text: "♫ (Clap Beat Intro) ♫" },
      { time: 4, text: "Light 'em up, up, up" },
      { time: 6, text: "Light 'em up, up, up" },
      { time: 8, text: "Light 'em up, up, up" },
      { time: 10, text: "I'm on fire!" },
      { time: 12, text: "Be careful making wishes in the dark" },
      { time: 15, text: "Darkness cannot drive out darkness" },
      { time: 18, text: "Only light can do that" },
      { time: 20, text: "I still feel the sparks" },
      { time: 23, text: "So light 'em up, up, up" },
      { time: 26, text: "My songs know what you did in the dark" }
    ]
  },
  {
    id: 'whatsup',
    title: "What's Up?",
    artist: "4 Non Blondes",
    album: "Bigger, Better, Faster, More!",
    duration: "4:55",
    durationSec: 295,
    cover: "linear-gradient(135deg, #8b5cf6 0%, #6d28d9 50%, #4c1d95 100%)",
    gradientColors: ["#8b5cf6", "#6d28d9", "#4c1d95"],
    audioUrl: "https://www.soundhelix.com/examples/mp3/SoundHelix-Song-8.mp3",
    lyrics: [
      { time: 0, text: "♫ (Acoustic Guitar Strumming Intro) ♫" },
      { time: 15, text: "Twenty-five years and my life is still" },
      { time: 19, text: "Trying to get up that great big hill of hope" },
      { time: 25, text: "For a destination" },
      { time: 29, text: "I realized quickly when I knew I should" },
      { time: 33, text: "That the world was made of this brotherhood of man" },
      { time: 39, text: "For whatever that means" },
      { time: 43, text: "And so I cry sometimes when I'm lying in bed" },
      { time: 48, text: "Just to get it all out, what's in my head" },
      { time: 51, text: "And I, I am feeling a little peculiar" },
      { time: 57, text: "And so I wake in the morning and I step outside" },
      { time: 62, text: "And I take a deep breath and I get real high" },
      { time: 66, text: "And I scream from the top of my lungs" },
      { time: 70, text: "\"What's going on?\"" },
      { time: 74, text: "And I say, hey-ey-ey-ey-ey" },
      { time: 79, text: "Hey-ey-ey, I say hey, what's going on?" },
      { time: 88, text: "And I say, hey-ey-ey-ey-ey" },
      { time: 93, text: "Hey-ey-ey, I say hey, what's going on?" }
    ]
  }
];
